// Emit an apply_patch diff. Does not write source files itself.
const fs=require('node:fs');
const path=require('node:path');
const postcss=require('postcss');
const root=path.resolve(__dirname,'..');
const edits={
 'src/pages/index/index.scss':{
  '.prototype-shell':'min-height:100vh; color:var(--color-text-primary); background:radial-gradient(ellipse at 20% 0%,#cdf4e9 0,transparent 48%),linear-gradient(165deg,#f0fbf7,#fff 80%);',
  '.topbar':'height:calc(144rpx + env(safe-area-inset-top)); padding:calc(env(safe-area-inset-top) + 28rpx) 34rpx 22rpx; background:transparent; border:0;',
  '.topbar-title':'font-size:40rpx; font-weight:800; color:var(--color-text-primary);',
  '.topbar-copy':'font-size:24rpx; margin-top:8rpx; color:#568077;',
  '.avatar-button':'width:64rpx; height:64rpx; border-radius:50%; color:#fff; background:var(--gradient-brand); font-size:29rpx;',
  '.page-scroll':'height:calc(100vh - 262rpx - env(safe-area-inset-top) - env(safe-area-inset-bottom));',
  '.screen':'padding:16rpx 28rpx 40rpx;',
  '.today-screen':'display:flex; flex-direction:column; padding-top:6rpx;',
  '.today-summary':'order:0; padding:24rpx 24rpx 14rpx; border:2rpx solid #fff; border-radius:38rpx; background:linear-gradient(140deg,#ecfbf5ed,#ffffffed); box-shadow:var(--shadow-card); color:var(--color-text-primary);',
  '.today-summary__head':'display:flex; align-items:center; justify-content:space-between; gap:12rpx;',
  '.today-summary__head view text:first-child':'font-size:30rpx; font-weight:750; color:#093e34;',
  '.today-summary__head view text:last-child':'font-size:22rpx; color:#667d73; line-height:1.55; margin-top:12rpx;',
  '.summary-ring':'width:134rpx; height:134rpx; padding:12rpx; border-radius:50%; flex:none; background:conic-gradient(#00a38f var(--progress),#d5eee5 0);',
  '.summary-ring>view':'display:flex; width:100%; height:100%; justify-content:center; align-items:center; flex-direction:column; gap:4rpx; border-radius:50%; background:#f4fcf8;',
  '.today-summary__head .summary-ring text:first-child':'font-size:32rpx; font-weight:800;',
  '.today-summary__head .summary-ring text:last-child':'font-size:20rpx; margin:0;',
  '.home-health':'display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); margin-top:20rpx; padding:20rpx 2rpx; border-radius:28rpx; background:#ffffffef;',
  '.home-health>view':'display:flex; align-items:center; flex-direction:column; gap:9rpx; min-width:0; border-right:1rpx solid var(--color-line);',
  '.home-health>view:last-child':'border:0;',
  '.home-health>view>view':'display:flex; width:46rpx; height:46rpx; align-items:center; justify-content:center; border-radius:50%; background:#e8faf3;',
  '.home-health>view>text':'font-size:21rpx; white-space:nowrap;',
  '.home-health>view>text:nth-of-type(2)':'font-size:33rpx; font-weight:750;',
  '.home-health>view>text:nth-of-type(2)>text':'font-size:17rpx; font-weight:500;',
  '.home-health>view>text:last-child':'font-size:17rpx; color:#159779;',
  '.today-summary__numbers':'margin-top:15rpx; padding-top:0; border:0;',
  '.today-summary__numbers>view':'display:flex; align-items:center; justify-content:center; gap:6rpx;',
  '.today-summary__numbers > view > text:first-child':'font-size:22rpx; color:#326956; font-weight:650;',
  '.today-summary__numbers > view > text:first-child text':'font-size:18rpx;',
  '.today-summary__numbers > view > text:last-child':'margin:0; font-size:18rpx; color:#6c8a7e;',
  '.prescription-head':'order:1; margin:28rpx 14rpx 10rpx;',
  '.prescription-head view text:first-child':'font-size:31rpx;',
  '.prescription-head view text:last-child':'font-size:20rpx; margin-top:4rpx;',
  '.prescription-head>text':'font-size:21rpx;',
  '.prescription-carousel':'position:relative; order:2; margin:0;',
  '.prescription-pagination':'min-height:35rpx; padding:0 14rpx 8rpx;',
  '.prescription-pagination>text':'font-size:20rpx;',
  '.prescription-swiper':'height:440rpx;',
  '.prescription-swiper swiper-item':'padding:0 2rpx 18rpx;',
  '.prescription-card':'height:414rpx; padding:24rpx; border:1rpx solid #fff; border-radius:36rpx; background:#ffffffed; box-shadow:var(--shadow-card);',
  '.task-heading view text:first-child':'font-size:25rpx;',
  '.task-heading view text:last-child':'font-size:19rpx; line-height:1.4;',
  '.task-heading > text':'font-size:20rpx;',
  '.task-main':'grid-template-columns:145rpx minmax(0,1fr); gap:22rpx; margin-top:16rpx;',
  '.task-media':'width:145rpx; height:130rpx; border-radius:25rpx; background:#e4f7ef;',
  '.prescription-art':'width:100%; height:100%;',
  '.task-title':'font-size:31rpx; font-weight:750; margin-top:8rpx;',
  '.task-copy':'font-size:22rpx; margin-top:6rpx;',
  '.tag-row text':'padding:5rpx 10rpx; font-size:18rpx; border-radius:8rpx; color:#168f76; background:#e6f7f1;',
  '.task-meta':'margin-top:14rpx; padding:12rpx 0; border-color:var(--color-line);',
  '.task-meta text:first-child':'font-size:18rpx;',
  '.task-meta text:last-child':'font-size:22rpx; margin-top:4rpx;',
  '.task-primary,.primary-button':'min-height:86rpx; display:flex; align-items:center; justify-content:center; border-radius:28rpx; background:var(--gradient-brand); box-shadow:0 8rpx 18rpx #087b6814; font-size:31rpx; font-weight:750;',
  '.task-primary':'min-height:72rpx; margin-top:10rpx; border-radius:999rpx; font-size:27rpx;',
  '.today-steps-card':'order:3; position:relative; width:100%; min-height:208rpx; margin-top:6rpx; padding:22rpx 140rpx 24rpx 27rpx; border:2rpx solid #fff; border-radius:34rpx; background:linear-gradient(125deg,#f2fdf8,#e7faf2); box-shadow:var(--shadow-card); text-align:left;',
  '.steps-magpie':'position:absolute; right:8rpx; bottom:16rpx; width:145rpx; height:150rpx;',
  '.today-steps-card__head':'display:block;',
  '.today-steps-card__icon':'display:none;',
  '.today-steps-card__head > view:nth-child(2) > text:first-child':'font-size:28rpx; color:#148877;',
  '.today-steps-card__head > view:nth-child(2) > text:nth-child(2)':'font-size:39rpx; color:#029a85; margin-top:10rpx;',
  '.today-steps-card__head > view:nth-child(2) > text:nth-child(2) text':'font-size:23rpx; color:#728078;',
  '.today-steps-card__head > text':'position:absolute; right:24rpx; top:21rpx; font-size:20rpx;',
  '.today-steps-card__source':'font-size:17rpx; margin-top:10rpx;',
  '.steps-progress':'height:12rpx; margin-top:14rpx; background:#dcedE5;',
  '.steps-progress > view':'background:var(--gradient-brand);',
  '.home-shortcuts':'order:4; display:grid; grid-template-columns:repeat(5,minmax(0,1fr)); padding:24rpx 4rpx; margin-top:18rpx; border-radius:30rpx; background:#fff; box-shadow:var(--shadow-card);',
  '.home-shortcuts>button':'display:flex; min-height:95rpx; align-items:center; justify-content:center; gap:13rpx; flex-direction:column; font-size:20rpx; color:#245346;',
  '.today-garden-entry':'order:5;',
  '.exercise-picker-heading':'order:6;',
  '.category-grid':'order:7; gap:10rpx;',
  '.inline-game-grid':'order:8;',
  '.self-selected-card':'order:9; border:1rpx solid #a9dccb; background:#effbf5;',
  '.today-garden-entry image':'width:70rpx; height:80rpx;',
  '.bottom-nav':'height:calc(118rpx + env(safe-area-inset-bottom)); padding:8rpx 12rpx env(safe-area-inset-bottom); border-top:1rpx solid #f1f8f4; background:#fffffff5; box-shadow:0 -8rpx 26rpx #14735208;',
  '.bottom-nav button':'position:relative; font-size:22rpx; color:#8e9994;',
  '.bottom-nav button > view':'width:48rpx; height:48rpx;',
  '.bottom-nav button.active':'color:#008e79;',
  '.bottom-nav .nav-assistant>view':'display:flex; width:76rpx; height:76rpx; margin-top:-23rpx; padding:3rpx; border:6rpx solid #fff; border-radius:50%; background:var(--gradient-brand); box-shadow:0 5rpx 17rpx #077a6630;',
  '.nav-mascot':'width:100%; height:100%;',
  '.detail-frame':'background:radial-gradient(ellipse at 10% 0%,#d9f6ed,transparent 48%),#f6fcf9;',
  '.detail-header':'height:calc(108rpx + env(safe-area-inset-top)); padding:calc(env(safe-area-inset-top) + 16rpx) 26rpx 16rpx; background:transparent; border:0;',
  '.detail-header > text':'font-size:34rpx; color:var(--color-text-primary); font-weight:750;',
  '.detail-header button':'width:66rpx; height:66rpx; border-radius:50%; background:#e5f5ee; color:#006d5c; font-size:45rpx;',
  '.detail-header button:last-child':'background:#e5f5ee; font-size:31rpx;',
  '.detail-scroll':'height:calc(100vh - 108rpx - env(safe-area-inset-top));',
  '.detail-content':'padding:18rpx 30rpx calc(38rpx + env(safe-area-inset-bottom));',
  '.secondary-button':'display:flex; min-height:86rpx; margin-top:14rpx; align-items:center; justify-content:center; border:1rpx solid #15967d; border-radius:26rpx; color:#0a7f66; background:#fff; font-size:29rpx;',
  '.precheck-section':'margin-bottom:20rpx; padding:27rpx; border:1rpx solid #fff; border-radius:34rpx; background:#fff; box-shadow:var(--shadow-card);',
  '.policy-banner':'border:0; border-radius:32rpx; padding:30rpx; background:#eaf7f1;',
  '.policy-banner view text:first-child':'font-size:30rpx; font-weight:750;',
  '.policy-banner view text:last-child':'font-size:24rpx; line-height:1.6;',
  '.symptom-list label':'min-height:84rpx; border-bottom:1rpx solid var(--color-line); font-size:28rpx;',
  '.profile-identity':'display:grid; padding:24rpx; grid-template-columns:100rpx 1fr auto; gap:8rpx 18rpx; margin-bottom:24rpx; border-radius:34rpx; background:#fff; box-shadow:var(--shadow-card);',
  '.profile-avatar':'grid-row:1/3; width:94rpx; height:94rpx; margin:0; border-radius:50%; font-size:40rpx; background:var(--gradient-brand);',
  '.profile-identity > text:nth-child(2)':'font-size:31rpx; font-weight:750;',
  '.profile-identity > text:nth-child(3)':'grid-column:2/4; font-size:22rpx; margin:0;',
  '.profile-identity > button':'grid-column:3; grid-row:1; margin:0; min-height:60rpx; padding:12rpx; border-radius:999rpx; color:#fff; background:var(--gradient-brand); font-size:19rpx;',
  '.profile-garden-main':'min-height:255rpx; padding:30rpx; background:linear-gradient(120deg,#e1f8ee,#f8fdfa);',
  '.profile-garden-main image':'width:205rpx; height:230rpx;',
  '.health-management-grid':'grid-template-columns:repeat(2,minmax(0,1fr)); gap:16rpx; padding:0; background:transparent; box-shadow:none;',
  '.health-management-grid>button':'min-height:136rpx; padding:16rpx; border:1rpx solid #e3f0e9; border-radius:26rpx; background:#fff;',
  '.profile-section':'padding:24rpx; margin-top:22rpx; border-radius:34rpx; background:#fff; box-shadow:var(--shadow-card);',
  '.demo-surface-note':'display:block; color:var(--color-text-tertiary); font-size:23rpx; line-height:1.6;',
  '.demo-surfaces .service-list>button':'justify-content:space-between;',
  '.today-numbers':'padding:20rpx 0; gap:0; border-radius:34rpx; background:#fff; box-shadow:var(--shadow-card);',
  '.today-numbers>view':'border-right:1rpx solid var(--color-line); border-radius:0; box-shadow:none;',
  '.today-numbers>view:last-child':'border:0;',
  '.today-numbers text:first-child':'color:var(--color-text-primary); font-size:52rpx;',
  '.metric-row':'gap:14rpx;',
  '.metric-row>view':'background:#fff; border-radius:30rpx; padding:28rpx 20rpx; box-shadow:var(--shadow-card);',
  '.latest-advice':'padding:30rpx; border-radius:34rpx; border:0; background:#fff; box-shadow:var(--shadow-card);',
  '.empty-card':'padding:30rpx; border-radius:30rpx; font-size:25rpx; background:#ffffffd9; color:var(--color-text-secondary);',
  '.is-training .detail-frame':'background:linear-gradient(145deg,#003e3c,#005c53 64%,#003e38);',
  '.is-training .detail-header>text':'color:#fff;',
  '.is-training .detail-header button':'background:#ffffff10; border:1rpx solid #71bbab; color:#fff;',
  '.training-detail':'padding:0 22rpx 30rpx; color:#e6fff5;',
  '.training-strip--compact':'padding:16rpx 4rpx; color:#fff; background:transparent;',
  '.training-timer text:first-child':'color:#fff; font-size:36rpx;',
  '.training-timer text:last-child':'color:#b6dbce; font-size:22rpx;',
  '.training-state':'color:#b5eede; font-size:25rpx;',
  '.live-vitals-inline':'color:#d3f7e6; background:#116457; border:1rpx solid #378575;',
  '.training-detail .exercise-controls':'display:grid; grid-template-columns:1fr 1fr; gap:18rpx; margin-top:22rpx;',
  '.training-detail .exercise-controls>button':'min-height:82rpx; border:2rpx solid #52b69c; border-radius:28rpx; color:#e7fff4; background:#126358; font-size:29rpx;',
  '.training-detail .exercise-controls>.danger-button':'color:#ffd5cc; border-color:#eab0a4; background:#ffffff08;',
  '.training-detail .primary-button':'background:linear-gradient(120deg,#45d86b,#00a744); color:#fff; border:2rpx solid #95f8b1; border-radius:40rpx;',
  '.training-detail .text-button':'color:#bfdfd5;',
  '.pause-message':'display:flex; align-items:center; justify-content:center; gap:28rpx; min-height:150rpx; margin-top:20rpx; border-radius:28rpx; background:#ffffff09;',
  '.pause-message>image':'width:130rpx; height:130rpx;',
  '.pause-message>view>text':'display:block; font-size:29rpx; line-height:1.7; color:#e5fff2;',
  '.is-report .detail-frame':'background:radial-gradient(ellipse at 50% 260rpx,#e0f8ed,#ffffff 600rpx);',
  '.result-hero':'padding:36rpx 20rpx; background:transparent; border:0; text-align:center;',
  '.result-hero>view':'width:215rpx; height:215rpx; border:18rpx solid #19bd91; box-shadow:0 0 0 14rpx #fff,0 12rpx 40rpx #1ca68122; background:#fff; color:#05483c; font-size:75rpx;',
  '.result-hero>text:nth-of-type(1)':'font-size:37rpx; line-height:1.5; font-weight:800; margin-top:36rpx;',
  '.comparison-card':'padding:27rpx; border:0; border-radius:34rpx; background:#fff; box-shadow:var(--shadow-card);',
  '.advice-card':'border-radius:34rpx; box-shadow:var(--shadow-card);',
  '.modal-mask':'background:rgba(0,28,25,.68);',
  '.modal-card':'width:600rpx; max-width:calc(100% - 54rpx); padding:30rpx; border-radius:34rpx; box-shadow:0 24rpx 70rpx #001b1833;',
  '.danger-modal>button':'min-height:82rpx; padding:17rpx 20rpx; border:1rpx solid #e2e7e4; border-radius:22rpx; color:#60352e; background:#fff; font-size:25rpx; text-align:left;',
  '.danger-modal>button.stop-now':'text-align:center; background:linear-gradient(125deg,#ff7466,#ef4848); color:#fff; border:0; border-radius:999rpx; font-weight:700;',
  '.danger-modal>button.cancel':'text-align:center; color:#147d65; background:#fff; border-color:#74b89f; border-radius:999rpx;',
  '.danger-modal .emergency-note':'display:block; font-size:22rpx; color:#7d8c84; line-height:1.5; margin-top:16rpx;',
  '.policy-version,.policy-phase,.policy-fields,.policy-source,.scenario-section':'padding:28rpx; border-radius:30rpx; border:0; background:#fff; box-shadow:var(--shadow-card);',
  '.policy-version>button':'min-height:68rpx; border-radius:999rpx; background:var(--gradient-brand); font-size:25rpx;',
  '.review-list>view':'padding:30rpx; border:1rpx solid #fff; border-radius:34rpx; box-shadow:var(--shadow-card);',
  '.review-list>view>view:last-child button:last-child':'color:#d7584c; background:#fff4f1; border:1rpx solid #edb6aa;',
  '.knowledge-detail-banner':'min-height:270rpx; border:0; border-radius:34rpx; background:linear-gradient(145deg,#dff7ed,#fff);',
  '.article-body':'padding:30rpx; border:0; border-radius:34rpx; box-shadow:var(--shadow-card);',
  '.article-body text':'font-size:28rpx; line-height:1.9; color:var(--color-text-secondary);',
  '.knowledge-video':'width:100%; height:540rpx; border:5rpx solid #fff; border-radius:34rpx; background:#093e32;',
  '.video-detail-content':'padding:16rpx 28rpx 38rpx; background:transparent;',
  '.video-detail-body':'padding:28rpx 0;',
 },
 'src/components/TrainingReports.vue':{
  '.report-tabs':'grid-template-columns:repeat(3,1fr); background:transparent; border:0; padding:0; border-radius:0; gap:10rpx;',
  '.report-tabs button':'position:relative; min-height:86rpx; font-size:28rpx; background:transparent;',
  '.report-tabs button.active':'background:transparent; box-shadow:none; color:var(--color-brand-pressed);',
  '.report-tabs button.active::after':"content:''; position:absolute; left:30%; right:30%; bottom:0; height:5rpx; border-radius:5rpx; background:var(--color-brand);",
  '.mini-report-entry':'display:flex; align-items:center; justify-content:space-between; gap:12rpx; min-height:156rpx; padding:28rpx; border:1rpx solid #b7ead8; border-radius:32rpx; background:linear-gradient(120deg,#e7fcf2,#f6fcf9); text-align:left;',
  '.mini-report-entry>view>text':'display:block;',
  '.mini-report-entry>view>text:first-child':'color:#086b53; font-size:31rpx; font-weight:750;',
  '.mini-report-entry>view>text:last-child':'margin-top:16rpx; font-size:23rpx; color:var(--color-text-secondary);',
  '.mini-report-entry>text':'color:#fff; padding:16rpx; border-radius:999rpx; background:var(--gradient-brand); font-size:23rpx;',
  '.report-list':'border-radius:32rpx;',
  '.report-list>button':'min-height:125rpx; padding:24rpx;',
  '.report-section':'border-radius:34rpx; padding:30rpx;',
  '.advice':'color:var(--color-text-secondary);',
 },
 'src/components/TrainingExperience.vue':{
  '.training-pane':'height:650rpx; border:2rpx solid #77b9a7; border-radius:28rpx; background:#254f44;',
  '.training-pane:nth-child(2)':'height:650rpx;',
  '.pane-heading':'top:18rpx; left:15%; right:15%; padding:9rpx 2rpx; border:1rpx solid #65c8a8; border-radius:999rpx; background:#00766190; font-size:23rpx;',
  '.segment-heading > text:first-child':'font-size:25rpx; color:#e4fff0;',
  '.segment-heading > text:last-child':'color:#a5edd2;',
  '.segment-dots view':'background:#256c5d;',
  '.segment-dots view.active':'background:#5be39e;',
  '.game-stage':'min-height:650rpx; background:linear-gradient(160deg,#145f54,#00473d); border:1rpx solid #58a995; color:#e6fff3;',
  '.game-title':'color:#fff;',
  '.game-kicker':'color:#9de9c9;',
  '.prototype-label':'color:#b0d9c8;',
  '.rep-count text:first-child':'color:#fff;',
  '.rhythm-stats view':'background:#ffffff0f; color:#c7eddc;',
  '.game-action, .beat-button':'background:linear-gradient(120deg,#36cb6b,#08a04b); border:1rpx solid #8cebb1; border-radius:28rpx;',
 },
 'src/components/StepIndicator.vue':{
  '.stepper':'margin:16rpx 0 30rpx;',
  '.step':'width:110rpx;',
  '.step > text':'width:58rpx; height:58rpx; font-size:28rpx; background:#e6f5ef;',
  '.step .small-text':'width:auto; height:auto; border-radius:0; margin-top:12rpx; background:transparent; font-size:25rpx;',
  '.step.active .small-text,.step.done .small-text':'background:transparent; color:var(--color-brand-pressed);',
  '.step-line':'width:100rpx; margin-top:28rpx;',
 },
 'src/components/CompanionHub.vue':{
  '.companion-entry-icon--buddy':'color:#11876d; background:#e3f7ee;',
  '.companion-hero':'background:linear-gradient(120deg,#d6f4e8,#f3fcf8); border-radius:34rpx;',
 },
 'src/components/DetailIntro.vue':{
  '.screen-title':'font-size:38rpx; font-weight:800; color:var(--color-text-primary);',
 },
};
const colors={'#1e293b':'var(--color-text-primary)','#0f172a':'var(--color-text-primary)','#64748b':'var(--color-text-secondary)','#475569':'var(--color-text-secondary)','#94a3b8':'var(--color-text-tertiary)','#0ea5a4':'var(--color-brand)','#0f766e':'var(--color-brand-pressed)','#ccfbf1':'var(--color-brand-soft)','#f8fafc':'var(--color-page)','#f1f5f9':'#edf6f1','#e2e8f0':'var(--color-line)'};
let patch='*** Begin Patch\n';
for(const [file, rules] of Object.entries(edits)) {
 const full=path.join(root,file);const original=fs.readFileSync(full,'utf8');
 const match=file.endsWith('.vue')?original.match(/<style[^>]*>([\s\S]*?)<\/style>/):null;
 const old=match?match[1]:original; const css=postcss.parse(old);
 css.walkDecls(d=>{ d.value=d.value.replace(/#[0-9a-f]{6}\b/gi,h=>colors[h.toLowerCase()]||h); if(d.prop==='font-size'&&/^\d+rpx$/.test(d.value)&&parseInt(d.value)<22)d.value='22rpx'; if(d.prop==='border-radius'&&d.value==='24rpx')d.value='var(--radius-card)'; });
 const normalize=s=>s.replace(/\s+/g,'').trim();
 // Consolidate identical top-level selectors while retaining their last cascade location.
 const selectorMap=new Map();
 for(const node of [...css.nodes]){if(node.type!=='rule')continue;const key=normalize(node.selector);const previous=selectorMap.get(key);if(previous){const existing=new Set(node.nodes.filter(n=>n.type==='decl').map(n=>n.prop));for(const d of previous.nodes){if(d.type==='decl'&&!existing.has(d.prop))node.prepend(d.clone());}previous.remove();}selectorMap.set(key,node);}
 for(const [selector, declaration] of Object.entries(rules)) {let rule=selectorMap.get(normalize(selector));if(!rule){rule=postcss.rule({selector});css.append(rule);selectorMap.set(normalize(selector),rule);}const parsed=postcss.parse('a{'+declaration+'}').first;for(const d of parsed.nodes){rule.nodes.filter(n=>n.type==='decl'&&n.prop===d.prop).forEach(n=>n.remove());rule.append(d.clone());}}
 // Format without changing rule meaning. Keep UniApp platform comments.
 css.walkRules(r=>{r.raws.before='\n';r.raws.between=' ';r.raws.after='\n';r.walkDecls(d=>{d.raws.before='\n  ';d.raws.between=': ';});});
 const next=match?original.replace(match[1], '\n'+css.toString().trim()+'\n'):css.toString().trim()+'\n';
 if(next===original)continue;
 patch+='*** Update File: '+full+'\n@@\n'+original.trimEnd().split('\n').map(l=>'-'+l).join('\n')+'\n'+next.trimEnd().split('\n').map(l=>'+'+l).join('\n')+'\n';
}
console.log(patch+'*** End Patch');
